//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinBarkod_1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class CokluB
    {
        public int Id { get; set; }
        public string Barkod { get; set; }
        public Nullable<int> Urunid { get; set; }
    }
}
