//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinBarkod_1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        public int Id { get; set; }
        public string ekran { get; set; }
        public Nullable<double> toplam { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> ayrac { get; set; }
    }
}
