//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinBarkod_1_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Barkod1Entities : DbContext
    {
        public Barkod1Entities()
            : base("name=Barkod1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<Terazi> Terazi { get; set; }
        public virtual DbSet<Satisid> Satisid { get; set; }
        public virtual DbSet<islem> islem { get; set; }
        public virtual DbSet<islemOzet> islemOzet { get; set; }
        public virtual DbSet<UrunGrup> UrunGrup { get; set; }
        public virtual DbSet<Barkod> Barkod { get; set; }
        public virtual DbSet<StokHareket> StokHareket { get; set; }
        public virtual DbSet<CokluB> CokluB { get; set; }
        public virtual DbSet<Sabit> Sabit { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<HızlıUrun> HızlıUrun { get; set; }
        public virtual DbSet<Sbt> Sbt { get; set; }
        public virtual DbSet<Hesap> Hesap { get; set; }
    
        public virtual ObjectResult<cokurun_Result> cokurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cokurun_Result>("cokurun");
        }
    
        public virtual ObjectResult<stok_Result> stok()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stok_Result>("stok");
        }
    }
}
