//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinBarkod_1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satisid
    {
        public int Satisid1 { get; set; }
        public Nullable<int> islemno { get; set; }
        public string Urunad { get; set; }
        public string Barkod { get; set; }
        public string Urungrup { get; set; }
        public string Birim { get; set; }
        public Nullable<double> Alisfiyat { get; set; }
        public Nullable<double> Satisfiyat { get; set; }
        public Nullable<double> Miktar { get; set; }
        public Nullable<double> Toplam { get; set; }
        public Nullable<double> Kdvtutari { get; set; }
        public string Odemesekli { get; set; }
        public Nullable<bool> İade { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Kullanici { get; set; }
        public Nullable<double> Satisfiyat2 { get; set; }
        public Nullable<double> Satisfiyat3 { get; set; }
        public Nullable<double> Satisfiyat4 { get; set; }
        public Nullable<double> Satisfiyat5 { get; set; }
    }
}
